### Embedding 계층 구현

In [1]:
import numpy as np
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [2]:
x = np.array([[0, 0, 1, 0, 0, 0, 0]])
print(np.dot(x, W))

[[6 7 8]]


In [3]:
W[2]  

array([6, 7, 8])

In [3]:
W[5]

array([15, 16, 17])

In [7]:
idx = np.array([1, 0, 3, 0])
W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [22]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out
    
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        dW[self.idx] = dout
        return None

In [23]:
embed = Embedding(W)
print(embed.forward(1))
print(embed.idx)
print(embed.grads[0])
dout = np.array([1,2,3])
embed.backward(dout)
print(embed.grads[0])

[3 4 5]
1
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [1 2 3]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
embed = Embedding(W)
print(embed.forward([1,3,1,3]))
print(embed.idx)
print(embed.grads[0])
dout = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
embed.backward(dout)
print(embed.grads[0])

[[ 3  4  5]
 [ 9 10 11]
 [ 3  4  5]
 [ 9 10 11]]
[1, 3, 1, 3]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [3 3 3]
 [0 0 0]
 [4 4 4]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out
    
#     def backward(self, dout):
#         dW, = self.grads
#         dW[...] = 0
#         for i, word_id in enumerate(self.idx):
#             dW[word_id] += dout[i]
#         return None
    
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None    

In [34]:
embed = Embedding(W)
print(embed.forward([1,3,1,3]))
print(embed.idx)
print(embed.grads[0])
dout = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
embed.backward(dout)
print(embed.grads[0])

[[ 3  4  5]
 [ 9 10 11]
 [ 3  4  5]
 [ 9 10 11]]
[1, 3, 1, 3]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [4 4 4]
 [0 0 0]
 [6 6 6]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
